function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
const rankValue=document.getElementById('rankValue'),rankSub=document.getElementById('rankSub'),rankConsole=document.getElementById('rankConsole'),consoleLog=document.getElementById('consoleLog');
function setRank(r){document.querySelectorAll('.rank-scale button').forEach(b=>b.classList.toggle('active',b.dataset.rank===String(r)));rankConsole.classList.remove('glitch');void rankConsole.offsetWidth;rankConsole.classList.add('glitch');const read=rankConsole.querySelector('.rank-readout');if(r==='NULL'){rankValue.textContent='NULL';rankSub.textContent='ERROR // NO EXISTE UN TECHO VÁLIDO';read.classList.add('is-null');consoleLog.innerHTML='<span>&gt; Nivel 13 detectado.</span><span>&gt; Violación del límite registrada.</span><span>&gt; Comparando jerarquías...</span><span style="color:white">&gt; ERROR: clasificación inexistente // NULL.</span>';toast('PROTOCOLO NULL ACTIVADO')}else{rankValue.textContent=r==='EX'?'RANGO EX':'RANGO '+r;rankSub.textContent=r==='EX'?'ANOMALÍA CLASIFICABLE':'TECHO DE CRECIMIENTO // REGISTRO ESTABLE';read.classList.remove('is-null')}}
document.querySelectorAll('.rank-scale button').forEach(b=>b.addEventListener('click',()=>setRank(b.dataset.rank)));document.getElementById('triggerNull').addEventListener('click',()=>setRank('NULL'));
document.querySelectorAll('.contract-card').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.contract-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');document.getElementById('contractName').textContent=c.dataset.contract}));document.getElementById('deployContract').addEventListener('click',()=>toast('RECONSTRUCCIÓN DESPLEGADA // '+document.getElementById('contractName').textContent));
document.querySelectorAll('.boss-card button').forEach((b,i)=>b.addEventListener('click',()=>{if(i===0){focusState={cam:focusViews.custodian,start:performance.now(),duration:5600};toast('THE REDACTED CUSTODIAN // INSPECCIÓN 3D')}else if(i===1){focusState={cam:focusViews.bailiff,start:performance.now(),duration:5600};toast('ASH BAILIFF // INSPECCIÓN 3D')}else toast('ARCHIVO BLOQUEADO // INDEX REDACTED')}));
document.querySelectorAll('.model-inspector button').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.focus;if(!focusViews[key])return;document.querySelectorAll('.model-inspector button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');focusState={cam:focusViews[key],start:performance.now(),duration:5200};toast('INSPECTOR 3D // '+btn.textContent.trim())}));
const breachColors={catacumba:[.52,.16,.055],cisterna:[.045,.36,.38],glaciar:[.28,.58,.88],fundicion:[.78,.20,.035],santuario:[.22,.08,.58]};
document.querySelectorAll('.breach-network__grid article').forEach(card=>card.addEventListener('click',()=>{const key=card.dataset.breach;document.querySelectorAll('.breach-network__grid article').forEach(x=>x.classList.remove('active'));card.classList.add('active');activeRiftColor=breachColors[key]||breachColors.santuario;focusState={cam:focusViews.rift,start:performance.now(),duration:4800};toast('BRECHA // '+card.querySelector('i').textContent.trim())}));

document.getElementById('exploreBtn').addEventListener('click',()=>{explore=true;document.body.style.overflow='hidden';document.getElementById('exploreOverlay').classList.add('active');document.getElementById('exploreOverlay').setAttribute('aria-hidden','false');canvas.requestPointerLock?.();toast('MODO EXPLORACIÓN ACTIVO')});
function exitExplore(){explore=false;document.body.style.overflow='';document.exitPointerLock?.();document.getElementById('exploreOverlay').classList.remove('active');document.getElementById('exploreOverlay').setAttribute('aria-hidden','true')}
document.getElementById('exitExplore').addEventListener('click',exitExplore);window.addEventListener('keydown',e=>{if(e.code==='Escape'&&explore)exitExplore()});document.getElementById('wishlistBtn').addEventListener('click',()=>toast('CANAL DE DESARROLLO // PRÓXIMAMENTE'));
let audioCtx=null,master=null,audioOn=false;function startAudio(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.038;master.connect(audioCtx.destination);const d=audioCtx.createOscillator(),g=audioCtx.createGain();d.type='sine';d.frequency.value=42;g.gain.value=.65;d.connect(g).connect(master);d.start();const d2=audioCtx.createOscillator(),g2=audioCtx.createGain();d2.type='triangle';d2.frequency.value=63;g2.gain.value=.13;d2.connect(g2).connect(master);d2.start()}audioCtx.resume();master.gain.setTargetAtTime(.038,audioCtx.currentTime,.2);audioOn=true;document.getElementById('soundToggle').textContent='AUDIO ON'}function stopAudio(){if(master&&audioCtx)master.gain.setTargetAtTime(0,audioCtx.currentTime,.12);audioOn=false;document.getElementById('soundToggle').textContent='AUDIO OFF'}document.getElementById('soundToggle').addEventListener('click',()=>audioOn?stopAudio():startAudio());

loadAll().then(()=>{document.querySelector('.boot__bar span').style.width='100%';document.querySelector('.boot__status').textContent='BRECHA CERO // ONLINE';setTimeout(()=>{document.getElementById('boot').classList.add('done');document.body.classList.add('ready')},500)}).catch(err=>{console.error(err);document.querySelector('.boot__status').textContent='ERROR DE CARGA // ejecuta con servidor local'});
