function resize(){const w=Math.floor(innerWidth*DPR),h=Math.floor(innerHeight*DPR);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';gl.viewport(0,0,w,h)}}
window.addEventListener('resize',resize);resize();
window.addEventListener('mousemove',e=>{mouse.x=(e.clientX/innerWidth-.5)*2;mouse.y=(e.clientY/innerHeight-.5)*2;if(explore&&document.pointerLockElement===canvas){yaw-=e.movementX*.0022;pitch=clamp(pitch-e.movementY*.0017,-1.1,1.1)}});
window.addEventListener('keydown',e=>keys[e.code]=true);window.addEventListener('keyup',e=>keys[e.code]=false);
function scrollState(){const max=document.documentElement.scrollHeight-innerHeight;scrollT=max?scrollY/max:0;const sections=[...document.querySelectorAll('.section')];let best=0,bestD=Infinity;sections.forEach((s,i)=>{const r=s.getBoundingClientRect(),d=Math.abs(r.top+innerHeight*.35);if(d<bestD){bestD=d;best=i}});if(best!==currentScene){currentScene=best;const names=['ORIGIN','INDEX','BREACH ZERO','SYSTEM','CONTRACTS','BOSSES','MOVEMENT','NULL'];document.getElementById('hudChapter').textContent=names[best]||'NULL'}document.getElementById('hudProgress').textContent=String(Math.round(scrollT*100)).padStart(2,'0')+'%'}
window.addEventListener('scroll',scrollState,{passive:true});scrollState();
function cameraForScroll(){const total=cameraPath.length-1,f=scrollT*total,i=Math.min(total-1,Math.floor(f)),u=smooth(f-i),a=cameraPath[i],b=cameraPath[i+1];const base={p:[lerp(a.p[0],b.p[0],u)+mouse.x*1.3,lerp(a.p[1],b.p[1],u)-mouse.y*.6,lerp(a.p[2],b.p[2],u)],t:[lerp(a.t[0],b.t[0],u),lerp(a.t[1],b.t[1],u),lerp(a.t[2],b.t[2],u)],f:lerp(a.f,b.f,u)};if(!focusState)return base;const q=(performance.now()-focusState.start)/focusState.duration;if(q>=1){focusState=null;document.querySelectorAll('.model-inspector button').forEach(b=>b.classList.remove('active'));return base}const blend=q<.18?smooth(q/.18):q>.82?smooth((1-q)/.18):1;const c=focusState.cam;return{p:[lerp(base.p[0],c.p[0],blend),lerp(base.p[1],c.p[1],blend),lerp(base.p[2],c.p[2],blend)],t:[lerp(base.t[0],c.t[0],blend),lerp(base.t[1],c.t[1],blend),lerp(base.t[2],c.t[2],blend)],f:lerp(base.f,c.f,blend)}}
function cameraExplore(dt){const fwd=[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)],right=[Math.cos(yaw),0,-Math.sin(yaw)],spd=(keys.ShiftLeft?13:6.5)*dt;if(keys.KeyW)explorePos=vadd(explorePos,vmul(fwd,spd));if(keys.KeyS)explorePos=vadd(explorePos,vmul(fwd,-spd));if(keys.KeyA)explorePos=vadd(explorePos,vmul(right,-spd));if(keys.KeyD)explorePos=vadd(explorePos,vmul(right,spd));explorePos[0]=clamp(explorePos[0],-25,25);explorePos[1]=clamp(explorePos[1],1.4,25);explorePos[2]=clamp(explorePos[2],-75,90);return{p:explorePos,t:vadd(explorePos,fwd),f:66}}

function bindMat(m){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,m.alb);gl.uniform1i(loc.alb,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,m.nor);gl.uniform1i(loc.norm,1);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,m.rough);gl.uniform1i(loc.rough,2);gl.uniform1f(loc.scale,m.scale);gl.uniform1f(loc.metal,m.metal)}
function render(now){requestAnimationFrame(render);const dt=Math.min(.04,(now-last)/1000);last=now;resize();const cam=explore?cameraExplore(dt):cameraForScroll();gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(.009,.010,.015,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const proj=M4.perspective(deg(cam.f),canvas.width/canvas.height,.08,230),view=M4.lookAt(cam.p,cam.t);
 if(objects.length){gl.useProgram(mainProg);gl.uniformMatrix4fv(loc.view,false,view);gl.uniformMatrix4fv(loc.proj,false,proj);gl.uniform3fv(loc.cam,cam.p);gl.uniform1f(loc.time,now*.001);gl.uniform1f(loc.fog0,26);gl.uniform1f(loc.fog1,104);gl.uniform3fv(loc.rift,activeRiftColor);let current='';for(const o of objects){if(!assets[o.meshKey])continue;if(o.mat!==current){bindMat(mats[o.mat]);current=o.mat}gl.bindVertexArray(assets[o.meshKey].vao);gl.uniformMatrix4fv(loc.model,false,o.model);gl.uniform3fv(loc.tint,o.tint);gl.uniform1f(loc.em,o.em);gl.drawArrays(gl.TRIANGLES,0,assets[o.meshKey].count)}}
 // translucent dimensional sheet behind frame
 if(glowMesh){gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);gl.useProgram(glowProg);gl.uniformMatrix4fv(gloc.view,false,view);gl.uniformMatrix4fv(gloc.proj,false,proj);gl.uniform1f(gloc.time,now*.001);gl.uniform3fv(gloc.color,activeRiftColor);gl.bindVertexArray(glowMesh.vao);const model=M4.trs([0,7.6,-58.15],[0,0,0],[4.4,8.0,1]);gl.uniformMatrix4fv(gloc.model,false,model);gl.drawArrays(gl.TRIANGLES,0,glowMesh.count);gl.depthMask(true);gl.disable(gl.BLEND)}
 gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);gl.useProgram(partProg);gl.uniformMatrix4fv(ploc.view,false,view);gl.uniformMatrix4fv(ploc.proj,false,proj);gl.uniform1f(ploc.time,now*.001);gl.bindVertexArray(particles.vao);gl.drawArrays(gl.POINTS,0,particles.count);gl.depthMask(true);gl.disable(gl.BLEND)
}
requestAnimationFrame(render);
